---
- name: Wait for SSH connection
  hosts: all 
  gather_facts: False 
  tasks:
    - name: Ensure SSH port open 
      wait_for: 
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH 
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
      vars:
        ansible_connecting: local
        ansible_python_interpreter: /usr/bin/python3


- name: Install Docker
  hosts: docker_server
  become: yes
  tasks:
    - name: Install Docker 
      yum:
        name: docker
        update_cache: yes 
        state: present 
    - name: Start docker daemon 
      systemd: 
        name: docker 
        state: started 
- name: Create new linux user 
  hosts: docker_server 
  become: yes 
  tasks: 
    - name: Create new linux user 
      user:
        name: nana
        group: adm, docker 

# - name: Install Docker-compose 

