version: '3.8'

services:
    mongodb:
        image: mongodb:latest
        ports:
            - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - my_volume:/data/db
volumes:
    my_volume:
        driver: local