#!/usr/bin/env groovy
// @Library('jenkins-shared-library@master')
def gv 
// gv = load 'CI_steps.groovy'
pipeline{
    agent any
    environment{
        PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:${env.PATH}"
        patch_version = "1.0.0"
        maven_version = "3.6.3"
        DOCKER_TAG = "1.0.0"
        // Dockerhub_Username = credentials('docker-hub-credentials').username
        // Dockerhub_Password = credentials('docker-hub-credentials').password
        Dockerhub_Repo = "aleksanderkirsten/simple-maven-app"
        DOCKERHUB_CREDS = credentials('docker-hub-credentials')
        // gv = load 'CI_steps.groovy'
    }
    stages{
        stage('Init') {
            steps {
                script {
                                    // Load the script in a stage, not in the environment block
                    gv = load 'Module_8_Build_Automation_CI_CD/Dynamically_Increment_Application_version_Jenkins_Pipeline/CI_step.groovy'
                }
            }
        }
                
        stage('Increment patch version'){
            steps{
                script{
                    patch_version = gv.Increment_Version(patch_version)
                }
                // patch_version = gv.Increment_Version(patch_version)
            }
        }

        stage('Build Java Application and clean old artifacts'){
            steps{
                script{
                    gv.Maven_clean_and_build('Module_8_Build_Automation_CI_CD/Dynamically_Increment_Application_version_Jenkins_Pipeline')
                }
            }
        }

        stage('Build Image with dynamic Docker Image Tag'){
            steps{
                dir('Module_8_Build_Automation_CI_CD/Dynamically_Increment_Application_version_Jenkins_Pipeline'){
                    script{
                        gv.Build_Docker_Image(Dockerhub_Repo, patch_version)
                    }
                }
                // gv.Build_Docker_Image(Dockerhub_Repo, patch_version)
            }
        }

        stage('Push Image to private Dockerfile repository'){
            steps{
                script{
                    gv.Push_Docker_Image(Dockerhub_Repo, patch_version, DOCKERHUB_CREDS_USR, DOCKERHUB_CREDS_PSW)
                }
                // gv.Push_Docker_Image(Dockerhub_Repo, patch_version, DOCKERHUB_CREDS.username, DOCKERHUB_CREDS.password)
            }
        }

        stage('Commit version update of Jenkinsfile back to Git repository'){
            steps{
                script{
                    gv.Commit_Version_Update("aleksanderkirsten", "aleksanderkirsten@example.com", "main", "Update Jenkinsfile version to ${patch_version}")
                }
                // gv.Commit_Version_Update("aleksanderkirsten", "aleksanderkirsten@example.com", "main", "Update Jenkinsfile version to ${patch_version}")
            }
        }
    }

    post{
        success{
            echo "Build succeeded. Version updated to ${patch_version}."
            echo "Docker image pushed to Docker Hub with tag: ${patch_version}."
        }
        failure{
            echo "Build failed. Please check the logs for details."
        }

    }
}