#!/usr/bin/env groovy
library identifier: 'jenkins-shared-library@main', retriever: modernSCM(
    [$class: 'GitSCMSource',
    remote: '',
    credentialsId: 'github-credentials'
    ]
)




pipeline{
    agent any 
    tools{
        maven 'Maven'
    }
    environment{
        patch_version = "1.0.${env.BUILD_NUMBER}"
    }
    stages{
        stage('Init') {
            steps {
                script {
                    echo "Loading the .groovy script"
                    // Load the script in a stage, not in the environment block
                    // gv = load 'Module_8_Build_Automation_CI_CD/Dynamically_Increment_Application_version_Jenkins_Pipeline/CI_step.groovy'
                    sh "echo ${patch_version}"
                    sh "sudo apt-get update" 
                    sh "sudo apt-get install -y docker.io"
                    sh "sudo apt-get install -y docker-compose"
                    sh "sudo systemctl start docker"
                    sh "sudo systemctl enable docker" 
                }
            }
        }

        stage('Build') {
            steps{
                script{
                    echo "Building Docker Image"
                    def dockerBuildCmd = "docker build -t aleksanderk534/simple-maven-app2:${patch_version} ."
                    sh "${dockerBuildCmd}"
                }
            }
        }

        stage('Push') {
            steps{
                script{
                    echo "Pushing Docker Image to Docker Hub"
                    def dockerLoginCmd = "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
                    def dockerPushCmd = "docker push aleksanderk534/simple-maven-app2:${patch_version}"
                    sh "${dockerLoginCmd}"
                    sh "${dockerPushCmd}"
                }
            }
        }



        stage('Deploy') {
            steps{
                script{
                    echo "Deploying Docker Image to EC2 Instance"
                    withCredentials([
                        string(credentialsId: 'ec2-instance-ip', variable: 'EC2_IP')
                    ]) {
                        def dockerCmd = "docker run -p 3080:3080 -d aleksanderk534/simple-maven-app2:${patch_version}"
                        sshagent(['aws_access_key_id']) {
                            sh "ssh -o StrictHostKeyChecking=no ec2-user@${EC2_IP} '${dockerCmd}'"
                        }
                    }
                }
            }
        }
    }
}