#!/usr/bin/env groovy
library identifier: 'jenkins-shared-library@main', retriever: modernSCM(
    [$class: 'GitSCMSource',
    remote: '',
    credentialsId: 'github-credentials'
    ]
)




pipeline{
    agent any 
    tools{
        maven 'Maven'
    }
    environment{

    }
    stages{
        stage('Init') {
            steps {
                script {
                    echo "Loading the .groovy script"
                    // Load the script in a stage, not in the environment block
                    // gv = load 'Module_8_Build_Automation_CI_CD/Dynamically_Increment_Application_version_Jenkins_Pipeline/CI_step.groovy'
                }
            }
        }

        stage('Build') {
            steps{
                script{
                    echo "Building Docker Image"
                    def dockerBuildCmd = "docker build -t aleksanderk534/simple-maven-app2:${patch_version} ."
                    sh "${dockerBuildCmd}"
                }
            }
        }

        stage('Push') {
            steps{
                script{
                    echo "Pushing Docker Image to Docker Hub"
                    def dockerLoginCmd = "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
                    def dockerPushCmd = "docker push aleksanderk534/simple-maven-app2:${patch_version}"
                    sh "${dockerLoginCmd}"
                    sh "${dockerPushCmd}"
                }
            }
        }

        stage('Deploy') {
            steps{
                script{
                    echo "Deploying Docker Image to EC2 Instance"
                    withCredentials([
                        string(credentialsId: 'ec2-instance-ip', variable: 'EC2_IP')
                    ]) {
                        def dockerComposeCmd = "docker-compose -f docker-compose.yml up --detach"
                        sshagent(['aws_access_key_id']) {
                            sh "scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@${EC2_IP}:/home/ec2-user/docker-compose.yml"
                            sh "ssh -o StrictHostKeyChecking=no ec2-user@${EC2_IP} '${dockerComposeCmd}'"
                        }
                    }
                }
            }
        }
    }
}